# Generated by Django 4.0.3 on 2022-04-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='front',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
